# Generated by Django 4.2.9 on 2025-02-24 10:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('role', models.CharField(choices=[('MANAGER', 'YÖNETİCİ'), ('CUSTOMER', 'MÜŞTERİ'), ('SELLER', 'SATICI'), ('ADMIN', 'ADMİN')], max_length=20)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(blank=True, max_length=40)),
                ('status', models.SmallIntegerField(choices=[(1, 'ACTIVE'), (2, 'PASSIVE'), (3, 'SUSPEND')], default=1)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
