# Generated by Django 4.2.9 on 2025-05-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_city_rename_name_user_first_name_user_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_number',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
