# Generated by Django 4.2.9 on 2025-05-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('tr', 'Tr'), ('en', 'En')], default='tr', max_length=2),
        ),
    ]
