# Generated by Django 4.2.9 on 2025-05-05 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_id_number'),
        ('products', '0010_remove_order_phone_number_alter_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='users.city'),
            preserve_default=False,
        ),
    ]
